apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - example-secret.yaml # Relative path to the encrypted files
  - yet_another_secret.yaml # Relative path to the encrypted files
